SConscript( "proj/org/xtreemfs/client/bin/xtfs_lsvol.SConscript" )
SConscript( "proj/org/xtreemfs/client/bin/xtfs_mkvol.SConscript" )
SConscript( "proj/org/xtreemfs/client/bin/xtfs_mount.SConscript" )
SConscript( "proj/org/xtreemfs/client/bin/xtfs_rmvol.SConscript" )
SConscript( "proj/org/xtreemfs/client/bin/xtfs_send.SConscript" )
SConscript( "proj/org/xtreemfs/client/bin/xtfs_stat.SConscript" )

Import( "build_conf" )
if build_conf.CheckCHeader( "xos_ams.h" ):
    SConscript( "proj/org/xtreemfs/client/policies/xos_ams_flog.SConscript" )
