package org.xtreemfs.common.monitoring.generatedcode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling XTREEMFS-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "Osd" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.38350.4.
 */
public class Osd implements OsdMBean, Serializable {

    /**
     * Variable for storing the value of "DeletionStageQueueLength".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.9".
     */
    protected Integer DeletionStageQueueLength = new Integer(1);

    /**
     * Variable for storing the value of "StorageStageQueueLength".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.8".
     */
    protected Integer StorageStageQueueLength = new Integer(1);

    /**
     * Variable for storing the value of "PreprocStageQueueLength".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.7".
     */
    protected Integer PreprocStageQueueLength = new Integer(1);

    /**
     * Variable for storing the value of "NumBytesTX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.6".
     */
    protected Long NumBytesTX = new Long(1);

    /**
     * Variable for storing the value of "NumBytesRX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.5".
     */
    protected Long NumBytesRX = new Long(1);

    /**
     * Variable for storing the value of "NumReplBytesRX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.4".
     */
    protected Long NumReplBytesRX = new Long(1);

    /**
     * Variable for storing the value of "FreeSpace".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.12".
     */
    protected Long FreeSpace = new Long(1);

    /**
     * Variable for storing the value of "NumObjsTX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.3".
     */
    protected Long NumObjsTX = new Long(1);

    /**
     * Variable for storing the value of "NumReplObjsRX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.2".
     */
    protected Long NumReplObjsRX = new Long(1);

    /**
     * Variable for storing the value of "NumDeletedFiles".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.11".
     */
    protected Long NumDeletedFiles = new Long(1);

    /**
     * Variable for storing the value of "NumObjsRX".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.1".
     */
    protected Long NumObjsRX = new Long(1);

    /**
     * Variable for storing the value of "NumOpenFiles".
     * The variable is identified by: "1.3.6.1.4.1.38350.4.10".
     */
    protected Integer NumOpenFiles = new Integer(1);


    /**
     * Constructor for the "Osd" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public Osd(SnmpMib myMib) {
    }


    /**
     * Constructor for the "Osd" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public Osd(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "DeletionStageQueueLength" variable.
     */
    public Integer getDeletionStageQueueLength() throws SnmpStatusException {
        return DeletionStageQueueLength;
    }

    /**
     * Getter for the "StorageStageQueueLength" variable.
     */
    public Integer getStorageStageQueueLength() throws SnmpStatusException {
        return StorageStageQueueLength;
    }

    /**
     * Getter for the "PreprocStageQueueLength" variable.
     */
    public Integer getPreprocStageQueueLength() throws SnmpStatusException {
        return PreprocStageQueueLength;
    }

    /**
     * Getter for the "NumBytesTX" variable.
     */
    public Long getNumBytesTX() throws SnmpStatusException {
        return NumBytesTX;
    }

    /**
     * Getter for the "NumBytesRX" variable.
     */
    public Long getNumBytesRX() throws SnmpStatusException {
        return NumBytesRX;
    }

    /**
     * Getter for the "NumReplBytesRX" variable.
     */
    public Long getNumReplBytesRX() throws SnmpStatusException {
        return NumReplBytesRX;
    }

    /**
     * Getter for the "FreeSpace" variable.
     */
    public Long getFreeSpace() throws SnmpStatusException {
        return FreeSpace;
    }

    /**
     * Getter for the "NumObjsTX" variable.
     */
    public Long getNumObjsTX() throws SnmpStatusException {
        return NumObjsTX;
    }

    /**
     * Getter for the "NumReplObjsRX" variable.
     */
    public Long getNumReplObjsRX() throws SnmpStatusException {
        return NumReplObjsRX;
    }

    /**
     * Getter for the "NumDeletedFiles" variable.
     */
    public Long getNumDeletedFiles() throws SnmpStatusException {
        return NumDeletedFiles;
    }

    /**
     * Getter for the "NumObjsRX" variable.
     */
    public Long getNumObjsRX() throws SnmpStatusException {
        return NumObjsRX;
    }

    /**
     * Getter for the "NumOpenFiles" variable.
     */
    public Integer getNumOpenFiles() throws SnmpStatusException {
        return NumOpenFiles;
    }

}
