package org.xtreemfs.common.monitoring.generatedcode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling XTREEMFS-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "Osd" MBean.
 */
public interface OsdMBean {

    /**
     * Getter for the "DeletionStageQueueLength" variable.
     */
    public Integer getDeletionStageQueueLength() throws SnmpStatusException;

    /**
     * Getter for the "StorageStageQueueLength" variable.
     */
    public Integer getStorageStageQueueLength() throws SnmpStatusException;

    /**
     * Getter for the "PreprocStageQueueLength" variable.
     */
    public Integer getPreprocStageQueueLength() throws SnmpStatusException;

    /**
     * Getter for the "NumBytesTX" variable.
     */
    public Long getNumBytesTX() throws SnmpStatusException;

    /**
     * Getter for the "NumBytesRX" variable.
     */
    public Long getNumBytesRX() throws SnmpStatusException;

    /**
     * Getter for the "NumReplBytesRX" variable.
     */
    public Long getNumReplBytesRX() throws SnmpStatusException;

    /**
     * Getter for the "FreeSpace" variable.
     */
    public Long getFreeSpace() throws SnmpStatusException;

    /**
     * Getter for the "NumObjsTX" variable.
     */
    public Long getNumObjsTX() throws SnmpStatusException;

    /**
     * Getter for the "NumReplObjsRX" variable.
     */
    public Long getNumReplObjsRX() throws SnmpStatusException;

    /**
     * Getter for the "NumDeletedFiles" variable.
     */
    public Long getNumDeletedFiles() throws SnmpStatusException;

    /**
     * Getter for the "NumObjsRX" variable.
     */
    public Long getNumObjsRX() throws SnmpStatusException;

    /**
     * Getter for the "NumOpenFiles" variable.
     */
    public Integer getNumOpenFiles() throws SnmpStatusException;

}
