/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_xtreemfs_sandbox_DirectIOReader */

#ifndef _Included_org_xtreemfs_sandbox_DirectIOReader
#define _Included_org_xtreemfs_sandbox_DirectIOReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_xtreemfs_sandbox_DirectIOReader
 * Method:    loadFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jobject JNICALL Java_org_xtreemfs_sandbox_DirectIOReader_loadFile
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
