// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: include/PBRPC.proto

package org.xtreemfs.foundation.pbrpc.generatedinterfaces;

public final class PBRPC {
  private PBRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.procId);
    registry.add(org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.dataIn);
    registry.add(org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.dataOut);
    registry.add(org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.interfaceId);
  }
  public static final int PROC_ID_FIELD_NUMBER = 50001;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Integer> procId =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  public static final int DATA_IN_FIELD_NUMBER = 50004;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> dataIn =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  public static final int DATA_OUT_FIELD_NUMBER = 50003;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      java.lang.Boolean> dataOut =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  public static final int INTERFACE_ID_FIELD_NUMBER = 50002;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      java.lang.Integer> interfaceId =
        com.google.protobuf.GeneratedMessage
          .newGeneratedExtension();
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023include/PBRPC.proto\022\016xtreemfs.pbrpc\032 g" +
      "oogle/protobuf/descriptor.proto:1\n\007proc_" +
      "id\022\036.google.protobuf.MethodOptions\030\321\206\003 \001" +
      "(\007:1\n\007data_in\022\036.google.protobuf.MethodOp" +
      "tions\030\324\206\003 \001(\010:2\n\010data_out\022\036.google.proto" +
      "buf.MethodOptions\030\323\206\003 \001(\010:7\n\014interface_i" +
      "d\022\037.google.protobuf.ServiceOptions\030\322\206\003 \001" +
      "(\007B3\n1org.xtreemfs.foundation.pbrpc.gene" +
      "ratedinterfaces"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.procId.internalInit(
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor().getExtensions().get(0),
              java.lang.Integer.class);
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.dataIn.internalInit(
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor().getExtensions().get(1),
              java.lang.Boolean.class);
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.dataOut.internalInit(
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor().getExtensions().get(2),
              java.lang.Boolean.class);
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.interfaceId.internalInit(
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor().getExtensions().get(3),
              java.lang.Integer.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
