SConscript( "proj/xtfs_lsvol/xtfs_lsvol.SConscript" )
SConscript( "proj/xtfs_mkvol/xtfs_mkvol.SConscript" )
SConscript( "proj/xtfs_mount/xtfs_mount.SConscript" )
SConscript( "proj/xtfs_rmvol/xtfs_rmvol.SConscript" )
SConscript( "proj/xtfs_stat/xtfs_stat.SConscript" )
