// See doc/idl_conventions.txt before modifying this file.

module org
{
  module xtreemfs # 2010030916
  {
    module interfaces
    {
      const string ONCRPC_SCHEME = "oncrpc";
      const string ONCRPCG_SCHEME = "oncrpcg";
      const string ONCRPCS_SCHEME = "oncrpcs";
      const string ONCRPCU_SCHEME = "oncrpcu";

      const string REPL_UPDATE_PC_NONE = "";
      const string REPL_UPDATE_PC_RONLY = "ronly";
      const string REPL_UPDATE_PC_WARONE = "WaR1";
      const string REPL_UPDATE_PC_WARA = "WaRa";
      
      const uint32_t REPL_FLAG_FULL_REPLICA = 1;
      const uint32_t REPL_FLAG_IS_COMPLETE = 2;
      const uint32_t REPL_FLAG_STRATEGY_RANDOM = 4;
      const uint32_t REPL_FLAG_STRATEGY_RAREST_FIRST = 8;
      const uint32_t REPL_FLAG_STRATEGY_SEQUENTIAL = 16;
      const uint32_t REPL_FLAG_STRATEGY_SEQUENTIAL_PREFETCHING = 32;

      const uint32_t SYSTEM_V_FCNTL_H_O_RDONLY = 0x0000;
      const uint32_t SYSTEM_V_FCNTL_H_O_WRONLY = 0x0001;
      const uint32_t SYSTEM_V_FCNTL_H_O_RDWR = 0x0002;
      const uint32_t SYSTEM_V_FCNTL_H_O_APPEND = 0x0008;
      const uint32_t SYSTEM_V_FCNTL_H_O_CREAT = 0x0100;
      const uint32_t SYSTEM_V_FCNTL_H_O_TRUNC = 0x0200;
      const uint32_t SYSTEM_V_FCNTL_H_O_EXCL = 0x0400;
      const uint32_t SYSTEM_V_FCNTL_H_O_SYNC = 0x0010;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFREG = 0x8000;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFDIR = 0x4000;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFLNK = 0xA000;

      const uint32_t XCAP_EXPIRE_TIMEOUT_S_MIN = 30;
      
      const uint32_t SERVICE_STATUS_AVAIL = 0;
      const uint32_t SERVICE_STATUS_TO_BE_REMOVED = 1;
      const uint32_t SERVICE_STATUS_REMOVED = 2;
    };
  };
};
