module org
{
  module xtreemfs # 2010012113
  {
    module interfaces
    {
      interface NettestInterface # 400
      {
        // Operations
        void nop() # 1;
        buffer ping(buffer data) #2;
      };
    };
  };
};
