module org
{
  module xtreemfs # 2010030314
  {
    module interfaces
    {
      interface NettestInterface # 400
      {
        // Operations
        void nop() # 1;
        void send_buffer( buffer data ) # 2;
        void recv_buffer( uint32_t size, out buffer data ) # 3;
      };
    };
  };
};
