module org # 1000
{
  module xtreemfs # 0
  {
    module interfaces # 0
    {
      typedef sequence<string> StringSet # 1;

      struct UserCredentials # 2
      {
        string user_id;
        StringSet group_ids;
        string password;
      };
    };
  };
};
