module org # 1000
{
  module xtreemfs # 0
  {
    module interfaces # 0
    {
      typedef sequence<string> StringSet # 1;

      struct UserCredentials # 2
      {
        string user_id;
        StringSet group_ids;
        string password;
      };

      struct VivaldiCoordinates # 3
      {
         double x_coordinate;
         double y_coordinate;
         double local_error;
      };
    };
  };
};
