module org
{
  module xtreemfs # 2009082618
  {
    module interfaces
    {
      typedef sequence<string> StringSet # 1;

      struct UserCredentials # 2
      {
        string user_id;
        StringSet group_ids;
        string password;
      };
    };
  };
};
