#!/bin/bash
set -e

# stop before remove
if [ "$1" = "remove" -o "$1" = "deconfigure" ]; then
  echo "Stopping dir, mrc, osd services..."
  if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d xtreemfs-dir stop
    invoke-rc.d xtreemfs-mrc stop
    invoke-rc.d xtreemfs-osd stop
  else
    /etc/init.d/xtreemfs-dir stop
    /etc/init.d/xtreemfs-mrc stop
    /etc/init.d/xtreemfs-osd stop
  fi
fi

exit 0
