#!/bin/bash
set -e
# this scripts uses the tool 'uuidgen'

#XTREEMFS_CONFIG_DIR=/etc/xos/xtreemfs/
#$XTREEMFS_CONFIG_DIR/postinstall_setup.sh
#_POSTINSTALL_

#echo "Installing vivaldi RC-links..."
#update-rc.d xtreemfs-vivaldi defaults > /dev/null

#echo "Re-starting vivaldi service if started..."
#if which invoke-rc.d >/dev/null 2>&1; then
#  invoke-rc.d xtreemfs-vivaldi try-restart
#else
#  /etc/init.d/xtreemfs-vivaldi try-restart
#fi

exit 0
