package org.xtreemfs.common.monitoring.generatedcode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling XTREEMFS-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "Dir" MBean.
 */
public interface DirMBean {

    /**
     * Getter for the "ServiceCount" variable.
     */
    public Integer getServiceCount() throws SnmpStatusException;

    /**
     * Getter for the "AddressMappingCount" variable.
     */
    public Integer getAddressMappingCount() throws SnmpStatusException;

}
