package org.xtreemfs.common.monitoring.generatedcode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling XTREEMFS-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "Mrc" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.38350.3.
 */
public class Mrc implements MrcMBean, Serializable {

    /**
     * Variable for storing the value of "VolumeCount".
     * The variable is identified by: "1.3.6.1.4.1.38350.3.1".
     */
    protected Integer VolumeCount = new Integer(1);


    /**
     * Constructor for the "Mrc" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public Mrc(SnmpMib myMib) {
    }


    /**
     * Constructor for the "Mrc" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public Mrc(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "VolumeCount" variable.
     */
    public Integer getVolumeCount() throws SnmpStatusException {
        return VolumeCount;
    }

}
