package org.xtreemfs.common.monitoring.generatedcode;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling XTREEMFS-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "Mrc" MBean.
 */
public interface MrcMBean {

    /**
     * Getter for the "VolumeCount" variable.
     */
    public Integer getVolumeCount() throws SnmpStatusException;

}
