#! /usr/bin/env bash
cat > /dev/null << EndOfLicence
s3-bash
Copyright 2007 Raphael James Cohn

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
in compliance with the License.
You may obtain a copy of the License at
 
 	http://www.apache.org/licenses/LICENSE-2.0
 	
Unless required by applicable law or agreed to in writing, software distributed under the License
is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
or implied. See the License for the specific language governing permissions and limitations under
the License.
EndOfLicence

# Pragmas
set -u
set -e

readonly weAreKnownAs="$(basename $0)"
readonly ourPath="$(dirname $0)"

readonly commonFunctions="$ourPath/s3-common-functions"
if [ -e "$commonFunctions" ]; then
	source "$commonFunctions"
else
	version="Unknown"
	invalidEnvironmentExitCode=4
	printErrorHelpAndExit "$weAreKnownAs: Could not locate file s3-common-functions" $invalidEnvironmentExitCode
fi

function tests
{
	if [ ! -f secret-key ]; then
		printErrorHelpAndExit "Internal Error: No secret key file (secret-key) exists on the path"
	fi
	createTemporaryFile "somefile"
	somefile="$(mostRecentTemporaryFile)"
	echo "Testing" > "$somefile"
	url=/raphaelcohn-ami/somefile
	"$ourPath/s3-delete" -k $S3_SECRET_KEY -s "$ourPath/secret-key" $url
	if [ $? -ne 0 ]; then
		printErrorHelpAndExit "Internal Error: s3-delete failed"
	fi
	"$ourPath/s3-put" -T "$somefile" -k $S3_SECRET_KEY -s "$ourPath/secret-key" $url
	if [ $? -ne 0 ]; then
		printErrorHelpAndExit "Internal Error: s3-put failed"
	fi
	"$ourPath/s3-get" -k $S3_SECRET_KEY -s "$ourPath/secret-key" $url
	if [ $? -ne 0 ]; then
		printErrorHelpAndExit "Internal Error: s3-get failed"
	fi
	"$ourPath/s3-delete" -k $S3_SECRET_KEY -s "$ourPath/secret-key" $url
	if [ $? -ne 0 ]; then
		printErrorHelpAndExit "Internal Error: s3-delete failed"
	fi
}

function tarball
{
	tar -c s3-put s3-get s3-delete s3-common-functions Licence | gzip > "$temporaryDirectory/s3-bash.$version.tar.gz"
}

initialise
tests
tarball
