.TH xtfs_scrub 1 "April 2009" "The XtreemFS Distributed File System" "XtreemFS server"
.SH NAME
xtfs_scrub \- checks for each file in a volume if the MRC file size is outdated and if the checksum is correct. 
.SH SYNOPSIS
\fBxtfs_scrub [ \fIoptions\fB ] \fI<volume_name>\fB | \fIuuid:<volume_uuid>
.br

.SH DESCRIPTION
.I xtfs_scrub
performs a consistency check of each file in a given volume. The check compares the file size stored as part of the metadata to the actual file size defined by all objects of the file. If the metadata file size is outdated, it is corrected, granted that no \fI\-chk\fP switch is provided. In addition, an error is indicated if the file's checksum is not correct. The volume to scrub can either be specified by a name <volume_name> or a UUID 'uuid:<volume_uuid>' 

.SH EXAMPLE USAGE
.B "xtfs_scrub -dir oncrpc://localhost:32638 myVolume
.PP
Scrubs all files in the volume named 'myVolume' registered at the Directory Service 'oncrpc://localhost:32638'.

.SH OPTIONS
.TP
.TP
\fB-h\fP show usage info
.TP
\fB-dir\fP directory service to use (e.g. 'oncrpc://localhost:32638')
If no URI is specified, URI and security settings are taken from '/etc/xos/xtreemfs/default_dir'
In case of a secured URI ('oncrpcs://...'), it is necessary to also specify SSL settings (-c, -cp, -t, -tp).
.TP
\fB-c\fP  <creds_file>         a PKCS#12 file containing user credentials
.TP
\fB-cpass\fP <creds_passphrase>   a pass phrase to decrypt the the user credentials file
.TP
\fB-t\fP  <trusted_CAs>        a PKCS#12 file containing a set of certificates from trusted CAs
.TP
\fB-tpass\fP <trusted_passphrase> a pass phrase to decrypt the trusted CAs file
.TP
\fB\-chk\fP check only (do not update file sizes on the MRC in case of inconsistencies)
.TP
\fB\-thrs\fP  n  number of threads to use for scrubbing (default=10)


.SH "SEE ALSO"
.BR xtfs_mount (1),
.BR xtfs_umount (1),
.BR xtfs_showmount (1),
.BR xtfs_mkvol (1),
.BR xtfs_rmvol (1),
.BR xtfs_lsvol (1),
.BR xtfs_stat (1),
.BR xtfs_mrcdbtool (1)
.BR

.SH AVAILABILITY
The xtfs_mrcdbtool command is part of the XtreemFS-server package and is available from http://www.xtreemfs.org
