.TH xtfs_rmvol 1 "July 2008" "The XtreemFS Distributed File System" "XtreemFS client"
.SH NAME
xtfs_rmvol \- delete a volume and all files on this volume from a metadata server (MRC).
.SH SYNOPSIS
\fBxtfs_lsvol \fIvolume_URL\fR
.br

.SH DESCRIPTION
.I xtfs_rmvol
deletes the volume specified by
.I volume_URL
from the metadata server (MRC).
.B "Be careful, this command will delete the volume and all files on it!"

.SH EXAMPLE USAGE
.B "xtfs_rmvol http://remote.mrc.machine/myVolume"


.SH "SEE ALSO"
.BR xtfs_mount (1),
.BR xtfs_umount (1),
.BR xtfs_showmount (1),
.BR xtfs_mkvol (1),
.BR xtfs_lsvol (1),
.BR xtfs_stat (1),
.BR xtfs_sp (1),
.BR xtfs_scrub (1),
.BR xtfs_mrcdbtool (1)
.BR


.SH AVAILABILITY
The xtfs_rmvol command is part of the XtreemFS-client package and is available from http://www.XtreemFS.org