#!/bin/sh

### BEGIN INIT INFO
# Provides:          xtreemfs-dir
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     3 4 5
# Default-Stop:
# Short-Description: XtreemFS DIR
# Description:       XtreemFS DIR. http://www.xtreemfs.org/
### END INIT INFO

# Source function library.
if [ -e /lib/lsb/init-functions ]
then
	. /lib/lsb/init-functions
else
	. /etc/init.d/functions
fi

LOCKDIR=/var/lock/subsys
LOCKFILE=$LOCKDIR/xtreemfs-dir

XTREEMFS_USER=xtreemfs

PID_DS=/var/run/xtreemfs_dir.pid

CONFIG_DS=/etc/xos/xtreemfs/dirconfig.properties

LOG_DS=/var/log/xtreemfs/dir.log

if [ -z $JAVA_HOME ]; then
	export JAVA_HOME=/usr
fi
JAVA_CALL="$JAVA_HOME/bin/java -cp /usr/share/java/XtreemFS.jar:/usr/share/java/BabuDB.jar:/usr/share/java/yidl.jar:/usr/share/java/Foundation.jar"

pre_check() {

        exists=`grep -c $XTREEMFS_USER /etc/passwd`
        if [ $exists -eq 0 ]
        then
                echo "user $XTREEMFS_USER does not exist."
                exit 1
        fi
        dir=`dirname $LOG_DS`
        if [ ! -e $dir ]
        then
                echo "directory for logfiles $dir does not exist"
        fi
}

start() {
    if [ -f $LOCKFILE ]
    then
	echo -n "XtreemFS Directory Service (DIR) already started"
	echo
        return 0
    fi

    pre_check

    chown xtreemfs $LOG_DS
    echo >> $LOG_DS
    date >> $LOG_DS
    echo -e "Starting XtreemFS Directory Service (DIR)...\n\n" >> $LOG_DS

    rm $PID_DS
    echo -n "starting XtreemFS Directory Service (DIR)..."
    sudo -u $XTREEMFS_USER $JAVA_CALL org.xtreemfs.dir.DIR $CONFIG_DS >> $LOG_DS 2>&1 &
    PROCPID=$!
    echo $PROCPID > $PID_DS
    sleep 1s

    if [ -e /proc/$PROCPID ]
    then
	echo
    else
	echo
	return 1
    fi

    if [ ! -d $LOCKDIR ]; then mkdir -p $LOCKDIR; fi
    touch $LOCKFILE
    return 0
}

stop() {
    if [ -f $PID_DS ]
    then
        echo -n "stopping XtreemFS Directory Service (DIR)..."
        killproc -p $PID_DS java
	echo
    fi

    rm -f $LOCKFILE
    return 0
}

status() {
    if [ -f $PID_DS ]
    then
        PROCPID=`cat $PID_DS`
	if [ ! -e /proc/$PROCPID ]
	then
		echo "XtreemFS Directory Service (DIR) has crashed"
		return 1
	else
		echo "XtreemFS Directory Service (DIR) is running"
		return 0
	fi
    else
	echo "XtreemFS Directory Service (DIR) is not running"
	return 3
    fi
}

# See how we were called.
case "$1" in
    start)
        start
        result=$?
        ;;
    stop)
        stop
        result=$?
        ;;
    status)
        status
        result=$?
        ;;
    reload)
        result=0
        ;;
    restart)
        stop && sleep 1 && start
        result=$?
        ;;
    try-restart)
        ## Stop the service and if this succeeds (i.e. the
        ## service was running before), start it again.
        $0 status >/dev/null && $0 restart
        result=$?
        ;;
    *)
        echo -e "Usage: $0 {start|stop|restart|reload|status|try-restart}\n"
        result=1
        ;;
esac

exit $result
