// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbrpc/Ping.proto

package org.xtreemfs.foundation.pbrpc.generatedinterfaces;

public final class Ping {
  private Ping() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PingRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use PingRequest.newBuilder() to construct.
    private PingRequest() {
      initFields();
    }
    private PingRequest(boolean noInit) {}
    
    private static final PingRequest defaultInstance;
    public static PingRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingRequest_fieldAccessorTable;
    }
    
    // required string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    // required bool sendError = 2;
    public static final int SENDERROR_FIELD_NUMBER = 2;
    private boolean hasSendError;
    private boolean sendError_ = false;
    public boolean hasSendError() { return hasSendError; }
    public boolean getSendError() { return sendError_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasText) return false;
      if (!hasSendError) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasText()) {
        output.writeString(1, getText());
      }
      if (hasSendError()) {
        output.writeBool(2, getSendError());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      if (hasSendError()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getSendError());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest result;
      
      // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest();
        return builder;
      }
      
      protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.getDescriptor();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest getDefaultInstanceForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest) {
          return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest other) {
        if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasSendError()) {
          setSendError(other.getSendError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setText(input.readString());
              break;
            }
            case 16: {
              setSendError(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // required string text = 1;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
      
      // required bool sendError = 2;
      public boolean hasSendError() {
        return result.hasSendError();
      }
      public boolean getSendError() {
        return result.getSendError();
      }
      public Builder setSendError(boolean value) {
        result.hasSendError = true;
        result.sendError_ = value;
        return this;
      }
      public Builder clearSendError() {
        result.hasSendError = false;
        result.sendError_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.PingRequest)
    }
    
    static {
      defaultInstance = new PingRequest(true);
      org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.PingRequest)
  }
  
  public static final class PingResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use PingResponse.newBuilder() to construct.
    private PingResponse() {
      initFields();
    }
    private PingResponse(boolean noInit) {}
    
    private static final PingResponse defaultInstance;
    public static PingResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_fieldAccessorTable;
    }
    
    public static final class PingResult extends
        com.google.protobuf.GeneratedMessage {
      // Use PingResult.newBuilder() to construct.
      private PingResult() {
        initFields();
      }
      private PingResult(boolean noInit) {}
      
      private static final PingResult defaultInstance;
      public static PingResult getDefaultInstance() {
        return defaultInstance;
      }
      
      public PingResult getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_PingResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_PingResult_fieldAccessorTable;
      }
      
      // required string text = 1;
      public static final int TEXT_FIELD_NUMBER = 1;
      private boolean hasText;
      private java.lang.String text_ = "";
      public boolean hasText() { return hasText; }
      public java.lang.String getText() { return text_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasText) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasText()) {
          output.writeString(1, getText());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasText()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getText());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult result;
        
        // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult();
          return builder;
        }
        
        protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDescriptor();
        }
        
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult getDefaultInstanceForType() {
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult) {
            return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult other) {
          if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDefaultInstance()) return this;
          if (other.hasText()) {
            setText(other.getText());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setText(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string text = 1;
        public boolean hasText() {
          return result.hasText();
        }
        public java.lang.String getText() {
          return result.getText();
        }
        public Builder setText(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
          result.text_ = value;
          return this;
        }
        public Builder clearText() {
          result.hasText = false;
          result.text_ = getDefaultInstance().getText();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.PingResponse.PingResult)
      }
      
      static {
        defaultInstance = new PingResult(true);
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.PingResponse.PingResult)
    }
    
    public static final class PingError extends
        com.google.protobuf.GeneratedMessage {
      // Use PingError.newBuilder() to construct.
      private PingError() {
        initFields();
      }
      private PingError(boolean noInit) {}
      
      private static final PingError defaultInstance;
      public static PingError getDefaultInstance() {
        return defaultInstance;
      }
      
      public PingError getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_PingError_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_PingResponse_PingError_fieldAccessorTable;
      }
      
      // required string errorMessage = 1;
      public static final int ERRORMESSAGE_FIELD_NUMBER = 1;
      private boolean hasErrorMessage;
      private java.lang.String errorMessage_ = "";
      public boolean hasErrorMessage() { return hasErrorMessage; }
      public java.lang.String getErrorMessage() { return errorMessage_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        if (!hasErrorMessage) return false;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasErrorMessage()) {
          output.writeString(1, getErrorMessage());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasErrorMessage()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getErrorMessage());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError result;
        
        // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError();
          return builder;
        }
        
        protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDescriptor();
        }
        
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError getDefaultInstanceForType() {
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError) {
            return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError other) {
          if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDefaultInstance()) return this;
          if (other.hasErrorMessage()) {
            setErrorMessage(other.getErrorMessage());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setErrorMessage(input.readString());
                break;
              }
            }
          }
        }
        
        
        // required string errorMessage = 1;
        public boolean hasErrorMessage() {
          return result.hasErrorMessage();
        }
        public java.lang.String getErrorMessage() {
          return result.getErrorMessage();
        }
        public Builder setErrorMessage(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasErrorMessage = true;
          result.errorMessage_ = value;
          return this;
        }
        public Builder clearErrorMessage() {
          result.hasErrorMessage = false;
          result.errorMessage_ = getDefaultInstance().getErrorMessage();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.PingResponse.PingError)
      }
      
      static {
        defaultInstance = new PingError(true);
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.PingResponse.PingError)
    }
    
    // optional .xtreemfs.pbrpc.PingResponse.PingResult result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean hasResult;
    private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult result_;
    public boolean hasResult() { return hasResult; }
    public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult getResult() { return result_; }
    
    // optional .xtreemfs.pbrpc.PingResponse.PingError error = 2;
    public static final int ERROR_FIELD_NUMBER = 2;
    private boolean hasError;
    private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError error_;
    public boolean hasError() { return hasError; }
    public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError getError() { return error_; }
    
    private void initFields() {
      result_ = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDefaultInstance();
      error_ = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasResult()) {
        if (!getResult().isInitialized()) return false;
      }
      if (hasError()) {
        if (!getError().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasResult()) {
        output.writeMessage(1, getResult());
      }
      if (hasError()) {
        output.writeMessage(2, getError());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResult());
      }
      if (hasError()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getError());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse result;
      
      // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse();
        return builder;
      }
      
      protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDescriptor();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse getDefaultInstanceForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse) {
          return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse other) {
        if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.Builder subBuilder = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.newBuilder();
              if (hasResult()) {
                subBuilder.mergeFrom(getResult());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setResult(subBuilder.buildPartial());
              break;
            }
            case 18: {
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.Builder subBuilder = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .xtreemfs.pbrpc.PingResponse.PingResult result = 1;
      public boolean hasResult() {
        return result.hasResult();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult getResult() {
        return result.getResult();
      }
      public Builder setResult(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder setResult(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.Builder builderForValue) {
        result.hasResult = true;
        result.result_ = builderForValue.build();
        return this;
      }
      public Builder mergeResult(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult value) {
        if (result.hasResult() &&
            result.result_ != org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDefaultInstance()) {
          result.result_ =
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.newBuilder(result.result_).mergeFrom(value).buildPartial();
        } else {
          result.result_ = value;
        }
        result.hasResult = true;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.getDefaultInstance();
        return this;
      }
      
      // optional .xtreemfs.pbrpc.PingResponse.PingError error = 2;
      public boolean hasError() {
        return result.hasError();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError getError() {
        return result.getError();
      }
      public Builder setError(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasError = true;
        result.error_ = value;
        return this;
      }
      public Builder setError(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.Builder builderForValue) {
        result.hasError = true;
        result.error_ = builderForValue.build();
        return this;
      }
      public Builder mergeError(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError value) {
        if (result.hasError() &&
            result.error_ != org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDefaultInstance()) {
          result.error_ =
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.newBuilder(result.error_).mergeFrom(value).buildPartial();
        } else {
          result.error_ = value;
        }
        result.hasError = true;
        return this;
      }
      public Builder clearError() {
        result.hasError = false;
        result.error_ = org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.PingResponse)
    }
    
    static {
      defaultInstance = new PingResponse(true);
      org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.PingResponse)
  }
  
  public static final class Ping_emptyRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use Ping_emptyRequest.newBuilder() to construct.
    private Ping_emptyRequest() {
      initFields();
    }
    private Ping_emptyRequest(boolean noInit) {}
    
    private static final Ping_emptyRequest defaultInstance;
    public static Ping_emptyRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ping_emptyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_Ping_emptyRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_Ping_emptyRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest result;
      
      // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest();
        return builder;
      }
      
      protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.getDescriptor();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest getDefaultInstanceForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest) {
          return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest other) {
        if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.Ping_emptyRequest)
    }
    
    static {
      defaultInstance = new Ping_emptyRequest(true);
      org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.Ping_emptyRequest)
  }
  
  public static final class Ping_emptyResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use Ping_emptyResponse.newBuilder() to construct.
    private Ping_emptyResponse() {
      initFields();
    }
    private Ping_emptyResponse(boolean noInit) {}
    
    private static final Ping_emptyResponse defaultInstance;
    public static Ping_emptyResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ping_emptyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_Ping_emptyResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internal_static_xtreemfs_pbrpc_Ping_emptyResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse result;
      
      // Construct using org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse();
        return builder;
      }
      
      protected org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDescriptor();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse getDefaultInstanceForType() {
        return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse) {
          return mergeFrom((org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse other) {
        if (other == org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.Ping_emptyResponse)
    }
    
    static {
      defaultInstance = new Ping_emptyResponse(true);
      org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.Ping_emptyResponse)
  }
  
  public static abstract class PingService
      implements com.google.protobuf.Service {
    protected PingService() {}
    
    public interface Interface {
      public abstract void doPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse> done);
      
      public abstract void emptyPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PingService() {
        @Override
        public  void doPing(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request,
            com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse> done) {
          impl.doPing(controller, request, done);
        }
        
        @Override
        public  void emptyPing(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request,
            com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse> done) {
          impl.emptyPing(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.doPing(controller, (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest)request);
            case 1:
              return impl.emptyPing(controller, (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.getDefaultInstance();
            case 1:
              return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance();
            case 1:
              return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void doPing(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request,
        com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse> done);
    
    public abstract void emptyPing(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request,
        com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.doPing(controller, (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse>specializeCallback(
              done));
          return;
        case 1:
          this.emptyPing(controller, (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.getDefaultInstance();
        case 1:
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance();
        case 1:
          return org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void doPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.class,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance()));
      }
      
      public  void emptyPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.class,
            org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse doPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse emptyPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse doPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.getDefaultInstance());
      }
      
      
      public org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse emptyPing(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.getDefaultInstance());
      }
      
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_PingRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_PingRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_PingResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_PingResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_PingResponse_PingResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_PingResponse_PingResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_PingResponse_PingError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_PingResponse_PingError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_Ping_emptyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_Ping_emptyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_Ping_emptyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_Ping_emptyResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020pbrpc/Ping.proto\022\016xtreemfs.pbrpc\032\023incl" +
      "ude/PBRPC.proto\".\n\013PingRequest\022\014\n\004text\030\001" +
      " \002(\t\022\021\n\tsendError\030\002 \002(\010\"\275\001\n\014PingResponse" +
      "\0227\n\006result\030\001 \001(\0132\'.xtreemfs.pbrpc.PingRe" +
      "sponse.PingResult\0225\n\005error\030\002 \001(\0132&.xtree" +
      "mfs.pbrpc.PingResponse.PingError\032\032\n\nPing" +
      "Result\022\014\n\004text\030\001 \002(\t\032!\n\tPingError\022\024\n\014err" +
      "orMessage\030\001 \002(\t\"\023\n\021Ping_emptyRequest\"\024\n\022" +
      "Ping_emptyResponse2\305\001\n\013PingService\022P\n\006do" +
      "Ping\022\033.xtreemfs.pbrpc.PingRequest\032\034.xtre",
      "emfs.pbrpc.PingResponse\"\013\215\265\030\001\000\000\000\240\265\030\001\022[\n\t" +
      "emptyPing\022!.xtreemfs.pbrpc.Ping_emptyReq" +
      "uest\032\".xtreemfs.pbrpc.Ping_emptyResponse" +
      "\"\007\215\265\030\002\000\000\000\032\007\225\265\030\001\000\000\000B3\n1org.xtreemfs.found" +
      "ation.pbrpc.generatedinterfaces"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_xtreemfs_pbrpc_PingRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_xtreemfs_pbrpc_PingRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_PingRequest_descriptor,
              new java.lang.String[] { "Text", "SendError", },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingRequest.Builder.class);
          internal_static_xtreemfs_pbrpc_PingResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_xtreemfs_pbrpc_PingResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_PingResponse_descriptor,
              new java.lang.String[] { "Result", "Error", },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.Builder.class);
          internal_static_xtreemfs_pbrpc_PingResponse_PingResult_descriptor =
            internal_static_xtreemfs_pbrpc_PingResponse_descriptor.getNestedTypes().get(0);
          internal_static_xtreemfs_pbrpc_PingResponse_PingResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_PingResponse_PingResult_descriptor,
              new java.lang.String[] { "Text", },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingResult.Builder.class);
          internal_static_xtreemfs_pbrpc_PingResponse_PingError_descriptor =
            internal_static_xtreemfs_pbrpc_PingResponse_descriptor.getNestedTypes().get(1);
          internal_static_xtreemfs_pbrpc_PingResponse_PingError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_PingResponse_PingError_descriptor,
              new java.lang.String[] { "ErrorMessage", },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.PingResponse.PingError.Builder.class);
          internal_static_xtreemfs_pbrpc_Ping_emptyRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_xtreemfs_pbrpc_Ping_emptyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_Ping_emptyRequest_descriptor,
              new java.lang.String[] { },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyRequest.Builder.class);
          internal_static_xtreemfs_pbrpc_Ping_emptyResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_xtreemfs_pbrpc_Ping_emptyResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_Ping_emptyResponse_descriptor,
              new java.lang.String[] { },
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.class,
              org.xtreemfs.foundation.pbrpc.generatedinterfaces.Ping.Ping_emptyResponse.Builder.class);
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registerAllExtensions(registry);
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.registerAllExtensions(registry);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
