module org
{
  module xtreemfs
  {
    module interfaces
    {
      const uint8_t ACCESS_CONTROL_POLICY_NULL = 1;
      const uint8_t ACCESS_CONTROL_POLICY_POSIX = 2;
      const uint8_t ACCESS_CONTROL_POLICY_VOLUME = 3;

      const string ONCRPC_SCHEME = "oncrpc";
      const string ONCRPCS_SCHEME = "oncrpcs";

      const uint8_t OSD_SELECTION_POLICY_SIMPLE = 1;

      const string   REPL_UPDATE_PC_NONE = "";
      const string   REPL_UPDATE_PC_RONLY = "ronly";

      const uint16_t SERVICE_TYPE_MRC = 1;
      const uint16_t SERVICE_TYPE_OSD = 2;
      const uint16_t SERVICE_TYPE_VOLUME = 3;

      const uint8_t STRIPING_POLICY_DEFAULT = 0;
      const uint8_t STRIPING_POLICY_RAID0 = 1;

      const uint32_t SYSTEM_V_FCNTL_H_O_RDONLY = 0x0000;
      const uint32_t SYSTEM_V_FCNTL_H_O_WRONLY = 0x0001;
      const uint32_t SYSTEM_V_FCNTL_H_O_RDWR = 0x0002;
      const uint32_t SYSTEM_V_FCNTL_H_O_APPEND = 0x0008;
      const uint32_t SYSTEM_V_FCNTL_H_O_CREAT = 0x0100;
      const uint32_t SYSTEM_V_FCNTL_H_O_TRUNC = 0x0200;
      const uint32_t SYSTEM_V_FCNTL_H_O_EXCL = 0x0400;
    };
  };
};