module org
{
  module xtreemfs
  {
    module interfaces
    {
      const string ONCRPC_SCHEME = "oncrpc";
      const string ONCRPCS_SCHEME = "oncrpcs";
      const uint32_t ONCRPC_AUTH_FLAVOR = 1326;

      const string REPL_UPDATE_PC_NONE = "";
      const string REPL_UPDATE_PC_RONLY = "ronly";

      const uint32_t SYSTEM_V_FCNTL_H_O_RDONLY = 0x0000;
      const uint32_t SYSTEM_V_FCNTL_H_O_WRONLY = 0x0001;
      const uint32_t SYSTEM_V_FCNTL_H_O_RDWR = 0x0002;
      const uint32_t SYSTEM_V_FCNTL_H_O_APPEND = 0x0008;
      const uint32_t SYSTEM_V_FCNTL_H_O_CREAT = 0x0100;
      const uint32_t SYSTEM_V_FCNTL_H_O_TRUNC = 0x0200;
      const uint32_t SYSTEM_V_FCNTL_H_O_EXCL = 0x0400;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFREG = 0x8000;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFDIR = 0x4000;
      const uint32_t SYSTEM_V_FCNTL_H_S_IFLNK = 0xA000;
    };
  };
};