module xtreemfs
{
  module interfaces
  {
    struct AddressMapping
    {
      string uuid;
      uint64_t version;
      string protocol;
      string address;
      uint16_t port;
      string match_network;
      uint32_t ttl;
    };

    typedef sequence<AddressMapping> AddressMappingSet;

    interface DIRInterface # 1
    {
      void getAddressMappings( string uuid, out AddressMappingSet address_mappings ) # 1;
      uint64_t getGlobalTime() # 2;
    };
  };
};
