module xtreemfs
{
  module interfaces
  {
    interface Exceptions # 1
    {
      exception ProtocolException { uint32_t accept_stat; uint32_t error_code; string stack_trace; };
      exception errnoException { uint32_t error_code; string stack_trace; };
      exception RedirectException { string to_uuid; };
      exception ConcurrentModificationException { string stack_trace; };
    };
  };
};
