#include "types.idl"


module org
{
  module xtreemfs
  {
    module interfaces
    {
      struct NewFileSize
      {
        uint64_t size_in_bytes;
        uint32_t truncate_epoch;
      };

      typedef sequence<NewFileSize> NewFileSizeSet;

      struct OSDtoMRCData
      {
        uint8_t caching_policy;
        string data;
      };

      typedef sequence<OSDtoMRCData> OSDtoMRCDataSet;

      struct OSDWriteResponse 
      {
        NewFileSizeSet new_file_size;
        OSDtoMRCDataSet opaque_data;
      };

      struct StripingPolicy
      {
        uint8_t policy;
        uint32_t stripe_size;
        uint32_t width;
      };

      struct Replica
      {
        StripingPolicy striping_policy;
        uint32_t  replication_flags;
        StringSet osd_uuids;
      };

      typedef sequence<Replica> ReplicaSet;

      struct XCap
      {
        string file_id;
        uint32_t access_mode;
        uint64_t expires;
        string client_identity;
        uint32_t truncate_epoch;
        string server_signature;
      };

      struct XLocSet
      {
        ReplicaSet replicas;
        uint32_t   version;
        string     repUpdatePolicy;
        //used internally for read-only replication
        uint64_t   read_only_file_size;
      };

      struct FileCredentials
      {
        XLocSet xlocs;
        XCap    xcap;
      };

      typedef sequence<FileCredentials> FileCredentialsSet;
    };
  };
};
