module org
{
  module xtreemfs
  {
    module interfaces
    {
      // Log levels adapted from syslog
      enum LogLevel
      { 
        LOG_EMERG = 0,
        LOG_ALERT = 1,
        LOG_CRIT = 2,
        LOG_ERR = 3,
        LOG_WARNING = 4,
        LOG_NOTICE = 5,
        LOG_INFO = 6,
        LOG_DEBUG = 7
      };

      typedef sequence<string> StringSet;

      struct UserCredentials
      {
        string user_id;
        StringSet group_ids;
        string password;
      };

      struct VivaldiCoordinates 
      {
         double x_coordinate;
         double y_coordinate;
         double local_error;
      };
    };
  };
};
