module org
{
  module xtreemfs
  {
    module interfaces
    {
      typedef sequence<string> StringSet;

      struct UserCredentials
      {
        string user_id;
        StringSet group_ids;
        string password;
      };

      struct VivaldiCoordinates 
      {
         double x_coordinate;
         double y_coordinate;
         double local_error;
      };
    };
  };
};
