module org
{
  module xtreemfs
  {
    module interfaces
    {
      enum DebugLevel
      { 
        DEBUG_LEVEL_ERROR = 0,
        DEBUG_LEVEL_WARN = 1,
        DEBUG_LEVEL_INFO = 2,
        DEBUG_LEVEL_DEBUG = 3,
        DEBUG_LEVEL_TRACE = 4
      };

      typedef sequence<string> StringSet;

      struct UserCredentials
      {
        string user_id;
        StringSet group_ids;
        string password;
      };

      struct VivaldiCoordinates 
      {
         double x_coordinate;
         double y_coordinate;
         double local_error;
      };
    };
  };
};
