// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: include/Common.proto

package org.xtreemfs.pbrpc.generatedinterfaces;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface emptyRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code xtreemfs.pbrpc.emptyRequest}
   *
   * <pre>
   * Dummy message for requests without parameters.
   * The RPC implementation sends an empty message block.
   * </pre>
   */
  public static final class emptyRequest extends
      com.google.protobuf.GeneratedMessage
      implements emptyRequestOrBuilder {
    // Use emptyRequest.newBuilder() to construct.
    private emptyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private emptyRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final emptyRequest defaultInstance;
    public static emptyRequest getDefaultInstance() {
      return defaultInstance;
    }

    public emptyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private emptyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.class, org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<emptyRequest> PARSER =
        new com.google.protobuf.AbstractParser<emptyRequest>() {
      public emptyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new emptyRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<emptyRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xtreemfs.pbrpc.emptyRequest}
     *
     * <pre>
     * Dummy message for requests without parameters.
     * The RPC implementation sends an empty message block.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.class, org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.Builder.class);
      }

      // Construct using org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyRequest_descriptor;
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest getDefaultInstanceForType() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.getDefaultInstance();
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest build() {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest buildPartial() {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest result = new org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest) {
          return mergeFrom((org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest other) {
        if (other == org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.emptyRequest)
    }

    static {
      defaultInstance = new emptyRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.emptyRequest)
  }

  public interface emptyResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code xtreemfs.pbrpc.emptyResponse}
   *
   * <pre>
   * Dummy message for responses without content.
   * The RPC implementation sends an empty message block.
   * </pre>
   */
  public static final class emptyResponse extends
      com.google.protobuf.GeneratedMessage
      implements emptyResponseOrBuilder {
    // Use emptyResponse.newBuilder() to construct.
    private emptyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private emptyResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final emptyResponse defaultInstance;
    public static emptyResponse getDefaultInstance() {
      return defaultInstance;
    }

    public emptyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private emptyResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.class, org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<emptyResponse> PARSER =
        new com.google.protobuf.AbstractParser<emptyResponse>() {
      public emptyResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new emptyResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<emptyResponse> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xtreemfs.pbrpc.emptyResponse}
     *
     * <pre>
     * Dummy message for responses without content.
     * The RPC implementation sends an empty message block.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.class, org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.Builder.class);
      }

      // Construct using org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.internal_static_xtreemfs_pbrpc_emptyResponse_descriptor;
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse getDefaultInstanceForType() {
        return org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.getDefaultInstance();
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse build() {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse buildPartial() {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse result = new org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse) {
          return mergeFrom((org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse other) {
        if (other == org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.xtreemfs.pbrpc.generatedinterfaces.Common.emptyResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:xtreemfs.pbrpc.emptyResponse)
    }

    static {
      defaultInstance = new emptyResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:xtreemfs.pbrpc.emptyResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_emptyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_emptyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_xtreemfs_pbrpc_emptyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_xtreemfs_pbrpc_emptyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024include/Common.proto\022\016xtreemfs.pbrpc\"\016" +
      "\n\014emptyRequest\"\017\n\remptyResponseB(\n&org.x" +
      "treemfs.pbrpc.generatedinterfaces"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_xtreemfs_pbrpc_emptyRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_xtreemfs_pbrpc_emptyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_emptyRequest_descriptor,
              new java.lang.String[] { });
          internal_static_xtreemfs_pbrpc_emptyResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_xtreemfs_pbrpc_emptyResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_xtreemfs_pbrpc_emptyResponse_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
