#!/bin/bash

#####################################################################################
# Test for multithreaded OSD
# This script will start the server-side of the Httperf test.
# It starts the DIR and the OSD.
#
# At first it starts the DIR and the original OSD. The orininal OSD is needed for
# creating files at the OSD. Therefor the WriteFilesToOSD-class is necessary.
# After the creation-process the old OSD will be killed and the special
# HttperfOSD will be started.
# Now the user can start with the tests.
#
# The "*files_urls"-files contain the special URL-formatting which is used by
# the WriteFilesToOSD-class and httperf.
# It is necessary that you use the same "*files_urls"-file for the
# WriteFilesToOSD-class and httperf.
#
# You need to specify the following parameters for this script:
# OSD_FILEPATH: absolute path where OSD saves the files
# URLS_FILE: absolute path to the "*files_urls"-file
# FILESIZE: filesize of the files which will be created
#
#####################################################################################

$dir_pid
$osd1_pid
$osd2_pid
OSD_FILEPATH=$1
URLS_FILE=$2
FILESIZE=$3

rm -r /tmp/xtreemfs_httperf_test/
mkdir /tmp/xtreemfs_httperf_test/

# start DIR
echo "Starting Directory Service..."
$XTREEMFS/bin/xtreemfs_start ds -p 32638 -i -d http://localhost:32638 -c /tmp/xtreemfs_httperf_test/ds.cfg -s /tmp/xtreemfs_httperf_test/ds -l /tmp/xtreemfs_httperf_test/ds.log &
dir_pid=$!
echo "...Directory Service started (process Id = $dir_pid)."

echo
sleep 10

# start original OSD
echo "Starting OSD_1..."
$XTREEMFS/bin/xtreemfs_start osd -p 32637 -i -d http://localhost:32638 -c /tmp/xtreemfs_httperf_test/osd.cfg -s $OSD_FILEPATH &
osd1_pid=$!
echo "...OSD_1 started (process Id = $osd1_pid)."

echo
sleep 10

cd java/build/classes
# start writing files
#rm -r $XTREEMFS/osdFilePath
echo "Starting writing files..."
$JAVA_HOME/bin/java org.xtreemfs.sandbox.httperf.WriteFilesToOSD localhost 32637 $URLS_FILE $FILESIZE
echo "...writing files completed."

echo
sleep 10

# kill original OSD
echo "kill OSD_1"
if [ -d /proc/$osd1_pid ]; then
    echo "Killing process $osd1_pid"
    kill  $osd1_pid
fi

echo
sleep 10

# start a second OSD
#echo "start second OSD"
#$XTREEMFS/bin/xtreemfs_start osd -p 32639 -i -d http://localhost:32638 -c /tmp/xtreemfs_httperf_test/osd2.cfg -s $OSD_FILEPATH &
#

#start adapted OSD (using MultithreadedStorageStage) for httperf
#echo "start HttPerfOSD"
#$JAVA_HOME/bin/java org.xtreemfs.sandbox.httperf.HttperfOSDMultithreaded /tmp/xtreemfs_httperf_test/osd.cfg &
#osd2_pid=$!


sleep 10

echo

echo "services are running"
echo "press a button to kill all services"
read key

#if [ -d /proc/$osd2_pid ]; then
#    echo "Killing process $osd2_pid"
#    kill $osd2_pid
#fi

#kill Directory Service
echo "kill Directory Service (process Id = $dir_pid)"
if [ -d /proc/$dir_pid ]; then
    echo "Killing process $dir_pid"
    kill  $dir_pid
fi
echo "services stopped"

#cd ../../src/org/xtreemfs/sandbox/httperf



usage() {
    cat <<EOF
Usage:
   $0 <ABSOLUTE PATH where OSD saves the files> <ABSOLUTE PATH to urls containing file> <FILESIZE of the files which will be created>

EOF
}
