.TH lsfs.xtreemfs 1 "July 2011" "The XtreemFS Distributed File System" "XtreemFS client"
.SH NAME
lsfs.xtreemfs - list all XtreemFS volumes on an MRC
.SH SYNOPSIS
\fBlsfs.xtreemfs [\fIoptions\fB] [pbrpc[g|s]://]\fImrc-host\fR[:\fIport\fR]
.br

.SH DESCRIPTION
.I lsfs.xtreemfs
lists all volumes located on the XtreemFS MRC running at \fImrc-host\fR:\fIport\fR.

.SH EXAMPLE USAGE
.B "lsfs.xtreemfs remote.mrc.machine

.SH OPTIONS

.TP
General Options:
.TP
.BI "-d, --log-level " EMERG|ALERT|CRIT|ERR|WARNING|NOTICE|INFO|DEBUG
The log level of the XtreemFS client.
.TP
.B "-h, --help"
Print help and exit.
.TP
.BI "-l, --log-file-path " log_file_path
Path to log file.

.TP
SSL Options:
.TP
.BI "--pem-certificate-file-path " certfile
Path to PEM certificate file (for SSL installations only).
.TP
.BI "--pem-private-key-file-path " file
Path to PEM private key file (for SSL installations only).
.TP
.BI "--pem-private-key-passphrase " pass
Passphrase for PEM private key file (for SSL installations only)
.TP
.BI "--pkcs12-file-path " file
Path to PKCS#12 file (for SSL installations only).
.TP
.BI "--pkcs12-passphrase " pass
Passphrase for PKCS#12 file (for SSL installations only).

.SH "SEE ALSO"
.BR mkfs.xtreemfs (1),
.BR mount.xtreemfs (1),
.BR rmfs.xtreemfs (1),
.BR umount.xtreemfs (1),
.BR xtfsutil (1)
.BR

.SH AVAILABILITY
The lsfs.xtreemfs command is part of the XtreemFS-client package and is available from \fIhttp://www.xtreemfs.org\fP.