.TH xtfs_umount 1 "April 2009" "The XtreemFS Distributed File System" "XtreemFS client"
.SH NAME
xtfs_umount \- mounts an XtreemFS volume
.SH SYNOPSIS
\fBxtfs_umount \fIvolume mountpoint
.br

.SH DESCRIPTION
.I xtfs_umount
umounts the volume that has been mounted to \fIvolume\fR. 

.SH EXAMPLE USAGE
.B "xtfs_umount /mnt"

.SH "SEE ALSO"
.BR fusermount (1),
.BR xtfs_mount (1),
.BR xtfs_sp (1),
.BR xtfs_mkvol (1),
.BR xtfs_rmvol (1),
.BR xtfs_lsvol (1),
.BR xtfs_stat (1),
.BR xtfs_scrub (1),
.BR xtfs_mrcdbtool (1)
.BR xtfs_cleanup (1)
.BR

.SH AVAILABILITY
The xtfs_umount command is part of the XtreemFS-client package and is available from http://www.xtreemfs.org