.TH xtfs_rmvol 1 "July 2009" "The XtreemFS Distributed File System" "XtreemFS client"
.SH NAME
xtfs_mkvol \- delete a volume including all files on an XtreemFS MRC
.SH SYNOPSIS
\fBxtfs_mkvol [\fIoptions\fB] [oncrpc[s]://]\fImrchost\fR[:\fIport\fR]/\fIvolume
.br

.SH DESCRIPTION
.I xtfs_rmvol
deletes the volume named \fIvolume\fR from the XtreemFS MRC running at \fImrchost\fR:\fIport\fR. Be careful, this command will delete the volume and all files on it!

.SH EXAMPLE USAGE
.B "xtfs_rmvol remote.mrc.machine/myVolume"

.SH OPTIONS
.TP
\fB\-d/\-\-debug=\fIlevel
debug level
.TP
\fB\-h/\-\-help
print help and exit
.TP
\fB\-t/\-\-timeout\-ms=\fImillis
request timeout in milliseconds
.TP
\fB\-\-cert/-\-pem\-certificate\-file\-path=\fIcertfile
PEM certificate file path (for SSL installations only)
.TP
\fB\-\-pass/\-\-pem\-private\-key\-passphrase=\fIpass
PEM private key passphrase (for SSL installations only)
.TP
\fB\-\-pkcs12\-file\-path=\fIfile
PKCS#12 file path (for SSL installations only)
.TP
\fB\-\-pkcs12\-passphrase=\fIpass
PKCS#12 file passphrase (for SSL installations only)
.TP
\fB\-\-pkey/\-\-pem\-private\-key\-file\-path=\fIfile
PEM private key file path

.SH "SEE ALSO"
.BR xtfs_cleanup (1),
.BR xtfs_lsvol (1),
.BR xtfs_mkvol (1),
.BR xtfs_mount (1),
.BR xtfs_mrcdbtool (1),
.BR xtfs_repl (1),
.BR xtfs_scrub (1),
.BR xtfs_sp (1),
.BR xtfs_stat (1),
.BR xtfs_umount (1)
.BR

.SH AVAILABILITY
The xtfs_rmvol command is part of the XtreemFS-client package and is available from http://www.xtreemfs.org