.TH xtfs_cleanup 1 "July 2009" "The XtreemFS Distributed File System" "XtreemFS server"
.SH NAME
xtfs_cleanup \- checks for each file on the OSD, if it has an entry at the Metadata Server (MRC). 
.SH SYNOPSIS
\fBxtfs_cleanup [ \fIoptions\fB ] \fIuuid:<osd_uuid>
.BR

.SH DESCRIPTION
.I xtfs_cleanup
Performs a check of each file on the given Object Storage Device (OSD) whether it is registered at a MRC or not. 

.SH EXAMPLE USAGE
.B "xtfs_cleanup uuid:4ef54-kl345-2l35jn-3k4jl"
.PP
Starts the cleanup process on the OSD identified by UUID '4ef54-kl345-2l35jn-3k4jl'.

.SH OPTIONS
.TP
.TP
\fB-c \fI<creds_file>
a PKCS#12 file containing user credentials for SSL-based server connections
.TP
\fB-cpass \fI<creds_passphrase>
a pass phrase to decrypt the the user credentials file for SSL-based server connections
.TP
\fB-deleteVolumes
volume deletion - deletes volumes that might be dead!
.TP
\fB-dir \fI<uri>
Specifies the directory service to use (e.g. 'oncrpc://localhost:32638'). If no URI is specified, URI and security settings are taken from '/etc/xos/xtreemfs/default_dir'. In case of a secured URI ('oncrpcs://...'), it is necessary to also specify SSL settings.
.TP
\fB-e
erase mode - all files will be removed without further request!
.TP
\fB-h
show usage info
.TP
\fB-i
interactive mode
.TP
\fB-p \fI<admin_passphrase>
the administrator password for password protection-enabled systems
.TP
\fB-r
restore mode - all files will be restored to directory '/lost+found/' at the volume they are located
.TP
\fB-stop
suspend the currently running cleanup
.TP
\fB-t \fI<trusted_CAs>
a PKCS#12 file containing a set of certificates from trusted CAs for SSL-based server connections
.TP
\fB-tpass \fI<trusted_passphrase>
a pass phrase to decrypt the trusted CAs file for SSL-based server connections

.SH "SEE ALSO"
.BR xtfs_lsvol (1),
.BR xtfs_mkvol (1),
.BR xtfs_mount (1),
.BR xtfs_mrcdbtool (1),
.BR xtfs_repl (1),
.BR xtfs_rmvol (1),
.BR xtfs_scrub (1),
.BR xtfs_sp (1),
.BR xtfs_stat (1),
.BR xtfs_umount (1)
.BR

.SH AVAILABILITY
The xtfs_cleanup command is part of the XtreemFS-server package and is available from http://www.xtreemfs.org.
