.TH xtfs_scrub 1 "January 2010" "The XtreemFS Distributed File System" "XtreemFS tools"
.SH NAME
xtfs_scrub \- checks for each file in a volume if the MRC file size is outdated and if the checksum of all objects is correct. The scrubber can also replace defective replicas in repair mode. 
.SH SYNOPSIS
\fBxtfs_scrub [ \fIoptions\fB ] \fI<volume_name>\fB
.br

.SH DESCRIPTION
.I xtfs_scrub
performs a consistency check of each file in a given volume. If run without -repair or -delete it will only perform checks and report problems. Th scrubber checks for file if the file size on the OSDs is stored on the MRC and fixes inconsistencies if run in the -repair mode. In addition, the scrubber checks the checksum for each object of a file if the checksums are enabled on the OSD.

For replicated files the scrubber will check each replica for objects with inccorect checksum. In addition, it marks full replicas that successfully copied all objects as "complete" replicas. In the -repair mode, the scrubber will also replace replicas that contain ramoved OSDs. An OSD must be marked as dead/removed with the xtfs_chstatus tool, otherwise the scrubber will consider the OSD as temporarily unavailable and won't replace the replica.

.SH EXAMPLE USAGE
.B "xtfs_scrub -dir oncrpc://localhost:32638 myVolume
.PP
Scrubs all files in the volume named 'myVolume' registered at the Directory Service 'oncrpc://localhost:32638'.

.SH OPTIONS
.TP
.TP
\fB-c \fI<creds_file>
a PKCS#12 file containing user credentials for SSL-based server connections
.TP
\fB-cpass \fI<creds_passphrase>
a pass phrase to decrypt the the user credentials file for SSL-based server connections
.TP
\fB\-delete
deletes files where the objects are lost because they were stored on a failed/removed OSD
.TP
\fB-dir \fI<uri>
Specifies the directory service to use (e.g. 'oncrpc://localhost:32638'). If no URI is specified, URI and security settings are taken from '/etc/xos/xtreemfs/default_dir'. In case of a secured URI ('oncrpcs://...'), it is necessary to also specify SSL settings.
.TP
\fB-h
show usage info
.TP
\fB\-repair
repair inconsistent file sizes and replace replicas on failed/removed OSD
.TP
\fB-t \fI<trusted_CAs>
a PKCS#12 file containing a set of certificates from trusted CAs for SSL-based server connections
.TP
\fB\-thrs \fI<#threads> 
number of threads to use for scrubbing (default=10)
.TP
\fB-tpass \fI<trusted_passphrase>
a pass phrase to decrypt the trusted CAs file for SSL-based server connections

.SH "SEE ALSO"
.BR lsfs.xtreemfs (1),
.BR mkfs.xtreemfs (1),
.BR mount.xtreemfs (1),
.BR rmfs.xtreemfs (1),
.BR umount.xtreemfs (1),
.BR xtfs_cleanup (1),
.BR xtfs_mrcdbtool (1),
.BR xtfs_repl (1),
.BR xtfs_sp (1),
.BR xtfs_stat (1),
.BR xtfs_chstatus (1)
.BR

.SH AVAILABILITY
The xtfs_scrub command is part of the XtreemFS-tools package and is available from http://www.xtreemfs.org
