import os.path


build_env = Environment()
build_env["CPPPATH"] = [os.path.abspath( "../../include" )]
build_conf = build_env.Configure()
Export( "build_env", "build_conf" )


SConscript( "proj/vivaldi_flog.SConscript" )

if build_conf.CheckCHeader( "xos_ams.h" ):
    SConscript( "proj/xos_ams_flog.SConscript" )
